version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.x

  pre_build:
    commands:
      - chmod +x built_image.sh
      - chmod +x push_image.sh
      - ./built_image.sh

  build:
    commands:
      - ./push_image.sh